"""
EduNova.AI Computer Science Knowledge Base
=========================================
Contains comprehensive academic content for Computer Science & Engineering subjects.
"""

CS_KNOWLEDGE = {
    'normalization': {
        'title': 'Database Normalization',
        'definition': 'Normalization is a systematic database design technique that organizes tables to minimize data redundancy and dependency. It involves dividing large tables into smaller, well-structured tables and defining relationships between them to protect data integrity.',
        'key_concepts': [
            'Data Redundancy and Anomalies (Insert, Update, Delete)',
            'Functional Dependency (FD) and Key Attributes',
            'First Normal Form (1NF) - Atomic values',
            'Second Normal Form (2NF) - No Partial Dependency',
            'Third Normal Form (3NF) - No Transitive Dependency',
            'Boyce-Codd Normal Form (BCNF) - LHS must be a Super Key'
        ],
        'detailed_notes': """
Normalization is essential for designing relational databases that are free of anomalies:
1. **Insertion Anomaly**: Inability to insert certain data without the presence of other data.
2. **Update Anomaly**: Inconsistent data state when updating redundant data copies.
3. **Deletion Anomaly**: Unintentional loss of data when deleting a record.

### Normal Forms Explained:

* **First Normal Form (1NF)**: A relation is in 1NF if and only if the domain of each attribute contains only atomic (indivisible) values, and there are no repeating groups.
* **Second Normal Form (2NF)**: A relation is in 2NF if it is in 1NF and every non-prime attribute is fully functionally dependent on the primary key. This means no partial dependency exists (i.e., a non-key attribute depending on a part of a composite primary key).
* **Third Normal Form (3NF)**: A relation is in 3NF if it is in 2NF and no non-prime attribute is transitively dependent on the primary key. In other words, for any non-trivial functional dependency $X \\rightarrow Y$, either $X$ is a superkey or $Y$ is a prime attribute.
* **Boyce-Codd Normal Form (BCNF)**: A relation is in BCNF if for every non-trivial functional dependency $X \\rightarrow Y$, $X$ must be a superkey. BCNF is stronger than 3NF because it eliminates anomalies that 3NF allows, such as when two overlapping candidate keys exist.
""",
        'exam_tips': 'For 10-mark questions, always show step-by-step decomposition of a relation. Identify the functional dependencies (FDs), find the candidate keys, check each normal form sequentially (1NF -> 2NF -> 3NF -> BCNF), and specify if the decomposition is dependency-preserving and lossless-join.',
        'formulas': [
            'Functional Dependency: X -> Y',
            'Closure of Attribute Set: X+',
            'Lossless Join: R1 \\cap R2 -> R1 or R1 \\cap R2 -> R2'
        ],
        'questions': [
            {
                'q': 'Explain 1NF, 2NF, and 3NF with suitable examples.',
                'a': '1NF requires atomic values. For example, a student table cannot have multiple phone numbers in a single cell. 2NF removes partial dependency: in a composite key (StudentID, CourseID), CourseName depends only on CourseID, which violates 2NF, so we split it. 3NF removes transitive dependency: if StudentID -> ZipCode and ZipCode -> City, then StudentID -> City is transitive, violating 3NF, so we split into Student-Zip and Zip-City tables.',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'Which normal form is strictly stronger than 3NF?',
                'a': 'Boyce-Codd Normal Form (BCNF) is strictly stronger than 3NF because it requires that for every non-trivial dependency X -> Y, X must be a superkey, whereas 3NF allows Y to be a prime attribute.',
                'options': ['1NF', '2NF', '3NF', 'BCNF'],
                'type': 'mcq'
            }
        ]
    },
    'paging': {
        'title': 'Paging Memory Management',
        'definition': 'Paging is a memory management scheme that eliminates the need for contiguous allocation of physical memory. It permits the physical address space of a process to be non-contiguous by mapping logical pages to physical frames.',
        'key_concepts': [
            'Logical vs Physical Address Space',
            'Page Table and Translation Lookaside Buffer (TLB)',
            'Page Size and Frame Size (always equal, powers of 2)',
            'Internal Fragmentation (no External Fragmentation)',
            'Page Faults and Demand Paging'
        ],
        'detailed_notes': """
In Paging, logical memory is divided into fixed-size blocks called **pages**, and physical memory is split into blocks of the same size called **frames**.

### Address Translation:
Every address generated by the CPU is divided into two parts:
1. **Page Number (p)**: Used as an index into a page table which contains the base address of each frame in physical memory.
2. **Page Offset (d)**: Combined with base address to define the physical memory address that is sent to the memory unit.

$$\\text{Logical Address} = (p, d)$$
$$\\text{Physical Address} = (f, d)$$

where $f$ is the frame number obtained from the Page Table.

### Memory Overhead and TLB:
Since the page table is kept in main memory, accessing a byte requires two memory accesses (one for page-table entry, one for actual byte). To solve this, a special fast lookup hardware cache called **Translation Lookaside Buffer (TLB)** is used.
* **TLB Hit**: The page number is found in the TLB; address translation takes minimal overhead.
* **TLB Miss**: The page table must be consulted, incurring a latency penalty, and the entry is loaded into the TLB for future access.
""",
        'exam_tips': 'Make sure to draw the page translation diagram showing CPU generating Logical Address (p, d), indexing into Page Table, retrieving frame number f, and combining it with offset d to access Physical Memory.',
        'formulas': [
            'Logical Address Space = Page Size * Number of Pages',
            'Physical Address Space = Frame Size * Number of Frames',
            'Effective Access Time (EAT) = Hit Ratio * (TLB access time + Memory access time) + (1 - Hit Ratio) * (TLB access time + 2 * Memory access time)'
        ],
        'questions': [
            {
                'q': 'Explain the concept of Paging and how address translation works.',
                'a': 'Paging splits logical memory into pages and physical memory into frames. The Page Map Table (PMT) stores the mapping. Address translation uses the page number (p) as an index to lookup the frame number (f) in the table, then appends the offset (d) to locate the precise physical address.',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'Paging suffers from which type of fragmentation?',
                'a': 'Internal fragmentation. Since memory is allocated in fixed-size pages, if a process requires slightly less than a page size, the remaining frame space is wasted internally.',
                'options': ['External fragmentation', 'Internal fragmentation', 'Segment fragmentation', 'No fragmentation'],
                'type': 'mcq'
            }
        ]
    },
    'deadlock': {
        'title': 'Deadlocks in Operating Systems',
        'definition': 'A deadlock is a state in which a set of processes are blocked because each process is holding a resource and waiting for another resource held by some other process in the set, creating a cycle of dependencies.',
        'key_concepts': [
            'Four Coffman Conditions (Mutual Exclusion, Hold & Wait, No Preemption, Circular Wait)',
            'Resource Allocation Graph (RAG)',
            'Deadlock Handling Strategies (Prevention, Avoidance, Detection & Recovery, Ignorance/Ostrich)',
            'Bankers Algorithm for Deadlock Avoidance',
            'Safe State vs Unsafe State'
        ],
        'detailed_notes': """
A deadlock situation can arise if and only if all of the following four conditions hold simultaneously in a system:
1. **Mutual Exclusion**: At least one resource must be held in a non-shareable mode (only one process can use it at a time).
2. **Hold and Wait**: A process must be holding at least one resource and waiting to acquire additional resources that are currently being held by other processes.
3. **No Preemption**: Resources cannot be preempted; a resource can be released only voluntarily by the process holding it after that process has finished its task.
4. **Circular Wait**: A set $\{P_0, P_1, ..., P_n\}$ of waiting processes must exist such that $P_0$ is waiting for a resource held by $P_1$, $P_1$ is waiting for a resource held by $P_2$, and $P_n$ is waiting for a resource held by $P_0$.

### Deadlock Avoidance - Banker's Algorithm:
Banker's algorithm is a resource allocation and deadlock avoidance algorithm that tests for safety by simulating the allocation for predetermined maximum possible claims of all resources, then makes an "s-state" decision to determine if allocation should be allowed.
* **Safe State**: A state is safe if there exists a safe sequence of processes such that all processes can execute without deadlocking.
* **Unsafe State**: An unsafe state is NOT a deadlock, but it may lead to a deadlock if processes request their maximum resources.
""",
        'exam_tips': 'For numerical questions on Banker\'s Algorithm, always create the "Need Matrix" first (Need = Max - Allocation). Then write down step-by-step checks for safety using the Work and Finish vectors to output the Safe Sequence.',
        'formulas': [
            'Need[i][j] = Max[i][j] - Allocation[i][j]',
            'Safety Condition: Need <= Work'
        ],
        'questions': [
            {
                'q': 'State and explain the four necessary conditions for deadlock.',
                'a': '1. Mutual Exclusion: resources are non-shareable. 2. Hold and Wait: processes hold resources while waiting for new ones. 3. No Preemption: resources cannot be forcibly taken. 4. Circular Wait: a closed chain of processes waiting for each other.',
                'marks': 8,
                'type': 'descriptive'
            },
            {
                'q': 'Which of the following is NOT a necessary condition for deadlock?',
                'a': 'Resource Preemption. In fact, No Preemption is the necessary condition. If preemption were allowed, deadlocks would be resolved.',
                'options': ['Mutual Exclusion', 'Hold and Wait', 'Resource Preemption', 'Circular Wait'],
                'type': 'mcq'
            }
        ]
    },
    'arrays': {
        'title': 'Array Data Structure',
        'definition': 'An array is a collection of items stored at contiguous memory locations. It is a linear data structure where elements of the same data type can be accessed randomly using their indices.',
        'key_concepts': [
            'Contiguous Memory Allocation',
            'Random Access with Constant Time O(1)',
            'Static vs Dynamic Arrays',
            'Base Address and Address Calculation',
            'Time Complexity of Operations (Access, Search, Insertion, Deletion)'
        ],
        'detailed_notes': """
Arrays are fundamental structures used to store multiple items of the same type.
Each element is identified by an index, usually starting at 0.

### Address Calculation in 1D Array:
The memory address of an element at index $i$ can be calculated using the base address:
$$\\text{Address}(A[i]) = \\text{BaseAddress} + i \\times W$$
where $W$ is the size of each element (width in bytes).

### Address Calculation in 2D Array:
For a 2D array of dimensions $M \\times N$:
1. **Row-Major Order** (elements stored row by row):
   $$\\text{Address}(A[i][j]) = \\text{BaseAddress} + (i \\times N + j) \\times W$$
2. **Column-Major Order** (elements stored column by column):
   $$\\text{Address}(A[i][j]) = \\text{BaseAddress} + (j \\times M + i) \\times W$$

### Performance Trade-offs:
* **Access**: $O(1)$ constant time.
* **Insertion / Deletion at End**: $O(1)$ amortized time.
* **Insertion / Deletion at Start/Middle**: $O(N)$ because elements must be shifted.
* **Search**: $O(N)$ for unsorted array, $O(\\log N)$ for sorted array using Binary Search.
""",
        'exam_tips': 'Remember to practice address calculation problems. University exams frequently ask to find the address of element A[i][j] in a 2D array stored in Row-Major or Column-Major order, given the base address and element width.',
        'formulas': [
            'Row-Major Address: Base + (i * Cols + j) * Width',
            'Col-Major Address: Base + (j * Rows + i) * Width'
        ],
        'questions': [
            {
                'q': 'Derive the address calculation formula for a 2D array in Row-Major and Column-Major order.',
                'a': 'In Row-Major order, to reach A[i][j], we must skip i full rows (each of size Cols) and then j elements. Hence, index offset is (i * Cols + j). Multiplying by width W gives the address: Base + (i * Cols + j) * W. In Column-Major order, we skip j columns (each of size Rows) and i elements, yielding: Base + (j * Rows + i) * W.',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'What is the time complexity of retrieving an element from an array by index?',
                'a': 'O(1). Arrays support direct random access because the address can be computed in constant time.',
                'options': ['O(1)', 'O(log N)', 'O(N)', 'O(N^2)'],
                'type': 'mcq'
            }
        ]
    },
    'linked lists': {
        'title': 'Linked List Data Structure',
        'definition': 'A linked list is a linear data structure where elements are not stored in contiguous memory locations. Instead, elements are stored in nodes, and each node points to the next node using a pointer/reference.',
        'key_concepts': [
            'Nodes containing Data and Next pointers',
            'Singly vs Doubly vs Circular Linked Lists',
            'Dynamic Memory Allocation (no size limit pre-allocation)',
            'Sequential Access (no Random Access)',
            'Insertion/Deletion efficiency compared to Arrays'
        ],
        'detailed_notes': """
Unlike arrays, linked lists do not store elements in contiguous memory. This allows for efficient insertion and deletion of elements without shifting, but eliminates the ability to perform random access.

### Types of Linked Lists:
1. **Singly Linked List**: Each node contains a data field and a reference (pointer) to the next node. The last node points to `NULL`.
2. **Doubly Linked List**: Each node contains data, a pointer to the next node, and a pointer to the previous node. This allows traversal in both directions.
3. **Circular Linked List**: The last node points back to the first node instead of pointing to `NULL`.

### Time Complexity:
* **Accessing element at index k**: $O(N)$ (requires traversing from Head node).
* **Insertion/Deletion at Head**: $O(1)$.
* **Insertion/Deletion in Middle (given pointer to previous node)**: $O(1)$.
* **Search**: $O(N)$.
""",
        'exam_tips': 'Always write clear algorithms with boundary checks (e.g., list is empty, inserting at head, deleting from tail) when asked to write code or pseudo-code for linked list operations.',
        'formulas': [
            'Node representation: struct Node { int data; Node* next; };'
        ],
        'questions': [
            {
                'q': 'Compare Arrays and Linked Lists based on insertion, deletion, and search operations.',
                'a': 'Arrays: Insertion/Deletion is O(N) due to element shifting; search is O(N) or O(log N) if sorted; random access is O(1). Linked Lists: Insertion/Deletion is O(1) if pointer is given; search is O(N); random access is not supported (O(N) traversal). Arrays have static sizing (usually); Linked Lists are dynamically sized.',
                'marks': 8,
                'type': 'descriptive'
            },
            {
                'q': 'What pointer modification is required to delete node B which lies between node A and node C in a Singly Linked List?',
                'a': 'A->next = B->next (or A->next = C). This bypasses B, allowing it to be safely freed.',
                'options': ['A->next = B', 'A->next = B->next', 'B->next = A', 'C->next = A'],
                'type': 'mcq'
            }
        ]
    },
    'routing': {
        'title': 'Network Routing Algorithms',
        'definition': 'Routing is the process of selecting paths in a network along which to send network traffic. Routing algorithms determine the optimal path for packets from source to destination across interconnected networks.',
        'key_concepts': [
            'Static vs Dynamic Routing',
            'Distance Vector Routing (Routing Information Protocol - RIP)',
            'Link State Routing (Open Shortest Path First - OSPF)',
            'Path Vector Routing (Border Gateway Protocol - BGP)',
            'Bellman-Ford and Dijkstra algorithms'
        ],
        'detailed_notes': """
Routing is a core function of the Network Layer (Layer 3) of the OSI model.

### Primary Routing Paradigms:
1. **Distance Vector Routing**:
   * Each router maintains a table containing the distance (cost) and next-hop to every destination.
   * Routers periodically share their entire routing table with immediate neighbors.
   * Based on the **Bellman-Ford algorithm**.
   * Suffers from the **Count-to-Infinity problem** during link failures, which is mitigated by split horizon, poison reverse, and route poisoning.

2. **Link State Routing**:
   * Each router floods info about its direct links (status, cost) to all routers in the network.
   * Each router builds a complete topological map of the network.
   * Routers run **Dijkstra\'s Shortest Path algorithm** locally to calculate the best route.
   * Used in OSPF protocol. Fast convergence, no routing loops, but consumes more CPU and memory.
""",
        'exam_tips': 'For numerical questions, Dijkstra\'s algorithm is highly popular. Always show step-by-step table updates with columns for Vertex, Shortest Distance, and Parent Node.',
        'formulas': [
            'Bellman-Ford: D_i(j) = min_k { c(i,k) + D_k(j) }',
            'Dijkstra complexity: O(V^2) or O(E + V log V) with heaps'
        ],
        'questions': [
            {
                'q': 'Distinguish between Distance Vector Routing and Link State Routing.',
                'a': 'Distance Vector routing routers only know neighbor info and pass their entire routing tables (RIP protocol, Bellman-Ford). Link State routing routers know the complete topology of the network and flood local link states (OSPF protocol, Dijkstra). Distance Vector has slow convergence and loop problems; Link State has fast convergence and no loops.',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'Which algorithm is used by Link State Routing to calculate the shortest path?',
                'a': 'Dijkstra\'s Algorithm. It computes the shortest path from a single source to all destinations.',
                'options': ['Bellman-Ford', 'Kruskal', 'Dijkstra', 'Floyd-Warshall'],
                'type': 'mcq'
            }
        ]
    },
    'osi model': {
        'title': 'OSI Reference Model',
        'definition': 'The Open Systems Interconnection (OSI) model is a conceptual framework that standardizes the functions of a telecommunication or computing system into seven abstract layers.',
        'key_concepts': [
            'Seven Layers (Physical, Data Link, Network, Transport, Session, Presentation, Application)',
            'Encapsulation and Decapsulation of Protocol Data Units (PDUs)',
            'Functions of each layer (framing, routing, end-to-end delivery)',
            'Physical devices at each layer (Hub, Switch, Router, Gateway)',
            'TCP/IP vs OSI model'
        ],
        'detailed_notes': """
The OSI model partitions data flow into seven logical layers:
1. **Physical Layer (Layer 1)**: Transmits raw bit streams over physical medium. Hubs, cables, repeaters operate here.
2. **Data Link Layer (Layer 2)**: Provides node-to-node data transfer and error/flow control (Framing, MAC addresses). Switches, Bridges operate here.
3. **Network Layer (Layer 3)**: Manages packet routing and forwarding across multiple networks (IP addressing, logical routing). Routers operate here.
4. **Transport Layer (Layer 4)**: Ensures reliable, end-to-end data delivery (TCP/UDP, segmentation, port numbering, congestion control).
5. **Session Layer (Layer 5)**: Manages sessions, dialog control, and synchronization between applications.
6. **Presentation Layer (Layer 6)**: Translates, encrypts/decrypts, and compresses data (Syntax translator, JPEG, ASCII).
7. **Application Layer (Layer 7)**: Provides network services directly to user applications (HTTP, FTP, DNS, SMTP).
""",
        'exam_tips': 'Memorize the layers from bottom to top using the mnemonic: "Please Do Not Throw Sausage Pizza Away". For any descriptive answer, list all 7 layers, draw a stack diagram, and state 2 primary functions for each layer.',
        'formulas': [
            'Segment (Transport PDU) -> Packet (Network PDU) -> Frame (Data Link PDU) -> Bits (Physical PDU)'
        ],
        'questions': [
            {
                'q': 'List and explain the functions of all layers of the OSI model.',
                'a': 'The layers are: Physical (bit transmission), Data Link (framing, error control), Network (routing, IP addressing), Transport (end-to-end reliability, TCP/UDP), Session (session management), Presentation (encryption, formatting), and Application (user interface, HTTP).',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'Which layer of the OSI model is responsible for routing packets across networks?',
                'a': 'Network Layer (Layer 3). It determines the logical path for packets using IP addresses and routing algorithms.',
                'options': ['Data Link Layer', 'Network Layer', 'Transport Layer', 'Application Layer'],
                'type': 'mcq'
            }
        ]
    },
    'sorting': {
        'title': 'Sorting Algorithms',
        'definition': 'Sorting is the process of arranging a collection of data elements in a specific order (typically ascending or descending). Popular sorting algorithms have varying time complexities and memory overheads.',
        'key_concepts': [
            'Time and Space Complexity (Best, Average, Worst)',
            'Stability in Sorting (maintaining relative order of equal keys)',
            'In-place vs Extra-memory algorithms',
            'Divide and Conquer (Merge Sort, Quick Sort)',
            'Comparison vs Non-comparison sorting'
        ],
        'detailed_notes': """
### Primary Sorting Algorithms:
1. **Bubble Sort / Selection Sort / Insertion Sort**:
   * Simple to implement, $O(N^2)$ average and worst-case time complexity.
   * Insertion sort has $O(N)$ best-case for nearly sorted arrays.

2. **Merge Sort**:
   * Divide and Conquer approach.
   * Splits array in half, recursively sorts halves, and merges them.
   * Time complexity is always $O(N \\log N)$.
   * Needs $O(N)$ auxiliary space (not in-place). Stable.

3. **Quick Sort**:
   * Divide and Conquer approach.
   * Selects a pivot, partitions elements around the pivot, and recursively sorts sub-arrays.
   * Average-case time complexity is $O(N \\log N)$.
   * Worst-case is $O(N^2)$ (when pivot selection is poor, e.g., already sorted array).
   * Space complexity is $O(\\log N)$ recursive stack space. Unstable.

4. **Heap Sort**:
   * Uses binary heap tree.
   * Time complexity is always $O(N \\log N)$, space complexity is $O(1)$ (in-place). Unstable.
""",
        'exam_tips': 'You should know how to trace the sorting steps for a given list of numbers (e.g., showing the state of the list after each pass of Quick Sort or Merge Sort). Pivot partitioning trace is extremely common.',
        'formulas': [
            'Merge Sort recurrence: T(N) = 2T(N/2) + O(N) -> O(N log N)',
            'Quick Sort worst-case recurrence: T(N) = T(N-1) + O(N) -> O(N^2)'
        ],
        'questions': [
            {
                'q': 'Explain Quick Sort algorithm and discuss its worst-case time complexity.',
                'a': 'Quick Sort selects a pivot, partitions elements such that elements smaller than pivot are on left and larger on right, and recursively sorts. Worst-case is O(N^2), occurring when the input array is already sorted or reverse-sorted and the first/last element is always chosen as pivot.',
                'marks': 10,
                'type': 'descriptive'
            },
            {
                'q': 'Which sorting algorithm has a guaranteed worst-case time complexity of O(N log N) and is stable?',
                'a': 'Merge Sort. It guarantees O(N log N) time in all cases and preserves the relative order of equal elements (stable), though it requires O(N) extra space.',
                'options': ['Quick Sort', 'Merge Sort', 'Heap Sort', 'Bubble Sort'],
                'type': 'mcq'
            }
        ]
    }
}


def find_relevant_content(query: str, subject_name: str = '') -> dict:
    """Fuzzy keyword matching function to locate the best knowledge base entry."""
    from app.services.smart_engine import get_best_match
    return get_best_match(query, subject_name)
